"""new attibutes on order

Revision ID: 21f945b93bfc
Revises: 
Create Date: 2025-10-17 11:29:04.155180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f945b93bfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_qty', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('order_delivry_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('order_updated_at', sa.String(length=50), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('product_tva',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_tva',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('product_price',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_updated_at')
        batch_op.drop_column('order_delivry_address')
        batch_op.drop_column('order_qty')

    # ### end Alembic commands ###
