"""adding humor field in user table

Revision ID: 62437215c622
Revises: 
Create Date: 2025-11-10 10:55:21.505669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62437215c622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_messages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_qty', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('order_delivry_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('order_updated_at', sa.String(length=50), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('product_tva',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_humor', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_humor')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_tva',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('product_price',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_updated_at')
        batch_op.drop_column('order_delivry_address')
        batch_op.drop_column('order_qty')

    op.drop_table('user_messages')
    # ### end Alembic commands ###
