"""upodate

Revision ID: 7c0d7309168f
Revises: 
Create Date: 2025-11-18 09:31:30.225262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c0d7309168f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_user_id', sa.Integer(), nullable=False),
    sa.Column('contact_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'contact_user_id')
    )
    op.drop_table('user_messages')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_sender_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('message_receiver_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('message_read', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('messages_message_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['message_sender_user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['message_receiver_user_id'], ['user_id'])
        batch_op.drop_column('message_user_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('product_tva',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_tva',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('product_price',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_message_user_id_fkey'), 'users', ['message_user_id'], ['user_id'])
        batch_op.drop_column('message_read')
        batch_op.drop_column('message_receiver_user_id')
        batch_op.drop_column('message_sender_user_id')

    op.create_table('user_messages',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], name=op.f('user_messages_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_messages_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'message_id', name=op.f('user_messages_pkey'))
    )
    op.drop_table('contacts')
    # ### end Alembic commands ###
