"""column user_humor  on table user

Revision ID: 8ab6310e518b
Revises: 21f945b93bfc
Create Date: 2025-11-07 11:01:32.619976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab6310e518b'
down_revision = '21f945b93bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_messages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('product_tva',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_humor', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_humor')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_tva',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('product_price',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('user_messages')
    # ### end Alembic commands ###
