"""test

Revision ID: a8840bf56934
Revises: 
Create Date: 2025-12-01 14:47:22.610313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8840bf56934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ingredient_name', sa.Text(), nullable=False),
    sa.Column('ingredient_gi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_id'),
    sa.UniqueConstraint('ingredient_name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_description', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=80), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('product_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('product_stock', sa.Integer(), nullable=False),
    sa.Column('product_stock_check', sa.Boolean(), nullable=False),
    sa.Column('product_price', sa.Float(precision=3, asdecimal=2), nullable=False),
    sa.Column('product_tva', sa.Float(precision=3, asdecimal=2), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_username', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_first_name', sa.String(length=50), nullable=True),
    sa.Column('user_last_name', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('user_birthdate', sa.DateTime(), nullable=True),
    sa.Column('user_city', sa.String(length=100), nullable=True),
    sa.Column('user_avatar', sa.String(length=30), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('user_bio', sa.Text(), nullable=True),
    sa.Column('user_humor', sa.Text(), nullable=True),
    sa.Column('user_active', sa.Boolean(), nullable=True),
    sa.Column('user_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_last_login', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_username')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('story_title', sa.String(length=120), nullable=False),
    sa.Column('story_body', sa.Text(), nullable=False),
    sa.Column('story_image', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('contacts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_user_id', sa.Integer(), nullable=False),
    sa.Column('contact_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'contact_user_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_subject', sa.String(length=100), nullable=False),
    sa.Column('message_body', sa.String(), nullable=True),
    sa.Column('message_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('message_sender_user_id', sa.Integer(), nullable=False),
    sa.Column('message_receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('message_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['message_receiver_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['message_sender_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_created_at', sa.String(length=50), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('order_delivry', sa.Boolean(), nullable=False),
    sa.Column('order_qty', sa.Integer(), nullable=False),
    sa.Column('order_delivry_address', sa.String(length=255), nullable=True),
    sa.Column('order_updated_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=False),
    sa.Column('recipe_body', sa.Text(), nullable=False),
    sa.Column('recipe_servings', sa.Integer(), nullable=False),
    sa.Column('recipe_prep_minutes', sa.Integer(), nullable=False),
    sa.Column('recipe_cook_minutes', sa.Integer(), nullable=False),
    sa.Column('user_user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('restaurants',
    sa.Column('restaurant_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_name', sa.String(length=50), nullable=False),
    sa.Column('restaurant_adress', sa.String(length=255), nullable=False),
    sa.Column('restaurant_phone_number', sa.String(length=15), nullable=True),
    sa.Column('restaurant_evaluation', sa.String(length=20), nullable=True),
    sa.Column('restaurant_description', sa.Text(), nullable=True),
    sa.Column('restaurant_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('restaurant_website', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('stories',
    sa.Column('story_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('story_title', sa.String(length=255), nullable=False),
    sa.Column('story_body', sa.Text(), nullable=False),
    sa.Column('story_image', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_table('recipes_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes_ingredients')
    op.drop_table('stories')
    op.drop_table('restaurants')
    op.drop_table('recipes')
    op.drop_table('orders')
    op.drop_table('messages')
    op.drop_table('contacts')
    op.drop_table('comments')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
