"""upodate

Revision ID: b4ff036478a4
Revises: 0166a62b3c22
Create Date: 2025-11-18 11:31:20.547879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ff036478a4'
down_revision = '0166a62b3c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('product_tva',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_tva',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('product_price',
               existing_type=sa.Float(precision=3, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
